<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="updater_config.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="SettingsFileMangerLibrary">
      <HintPath>..\..\Libraries\SettingsFileMangerLibrary\bin\Debug\net9.0\SettingsFileMangerLibrary.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
